//const url = 'https://api.giphy.com/v1/gifs/search?api_key=ZRF4er4xY70H55uFr1dFjYtjfzzg6NkC&q=&limit=25&offset=0&rating=g&lang=en';
const gifsearchword = 'unicorn';
const apikey = 'ZRF4er4xY70H55uFr1dFjYtjfzzg6NkC'; //My unique API key generated by Giphy
const path = `https://api.giphy.com/v1/gifs/search?api_key=${apikey}&q=${gifsearchword}`;

fetch(path).then(function(res) { //Returns the data to the console
    return res.json() 
}).then(function(json) {
    console.log(json.data[0].images.fixed_width.url) //Choosing the specific image type to display
    const outputEl = document.getElementById('output')
    let outputHTML = '' //Empty string to hold search results that will be added to the HTML page
    
    json.data.forEach(function(obj) { //Loop through the results
        console.log(obj.images.fixed_width.url)

        const url = obj.images.fixed_width.url //url for each search result
        const width = obj.images.fixed_width.width //width for each search result
        const height = obj.images.fixed_width.height //height for each search result
        const title = obj.title //alternate text for each search result
        outputHTML += `<img 
        src="${url}" 
        width="${width}" 
        height="${height}"
        alt="${title}"
        >`
    })

    outputEl.innerHTML = outputHTML
}).catch(function(err) { //Catch errors and display in console
    console.log(err.message)
})

